stages:
  - build
  - deploy
  - test

dev-build:
  stage: build
  runs-on: chilla76cheese
  only:
    - test-cicd
  script:
    - echo "dev build"

dev-deploy:
  stage: deploy
  runs-on: chilla76cheese
  only:
    - test-cicd
  script:
    - echo "dev deploy"